### ISSUE TITLE
Post a release

### ISSUE THREAD

**Issue by JL2210** [ryanmcgrath/svgalib-1#2]
[This](https://github.com/ryanmcgrath/svgalib-1/commits/e698d8c11f938bb6039a1791dc54c620c228d308) commit you have now is fairly stable, could you create a release so I could package it for [Chromebrew](https://github.com/skycocker/chromebrew)?
I think a good release number would be 2.0.0.

**Comment by ryanmcgrath** [comment]
Heya, I'd be happy to take a look at this in 2019 - pretty preoccupied with stuff for the remainder of the year. Set a reminder for myself to check this on Jan 5th, feel free to poke if I've not scoped it after that.

Happy holidays (or whatever you happen to celebrate~)!

**Comment by JL2210** [comment]
@ryanmcgrath?

**Comment by ryanmcgrath** [comment]
Haven’t forgotten - dealing with some personal stuff. Ping me again in a few days if I don’t hit this tomorrow. :(

**Comment by ryanmcgrath** [comment]
So, circling back to this... can you define what you mean/need by "release"? It's been ~8 years since I touched this, lol...

I don't mind doing it, but more info on what you need would help direction.

**Comment by JL2210** [comment]
Create a Git tag and a tarball of the repository. Like this:

'git tag v2.0.0 && git push origin :refs/tags/v2.0.0'

From there, you run this command. A tarball of the repository will be
located in your '~/Uploads' folder:

'git checkout v2.0.0 && rm -rf .git && mkdir ~/Uploads && make clean && tar
cpf ~/Uploads/svgalib-1-2.0.0.tar . && xz -z9e
~/Uploads/svgalib-1-2.0.0.tar'

From there, go to 'https://github.com/ryanmcgrath/svgalib-1/tags', select
the three dots with the light background on the 'v2.0.0' box and select
'Create release'. You then change the uppermost text box below 'Existing
tag' to say 'Version 2.0.0', and in the large text box, you write your
release notes. You then go into your file manager of choice, navigate to
'Uploads', and drop 'svgalib-1-2.0.0.tar.xz' on the box in your web browser
that has the large down arrow in it. You click 'Create release', and you're
done!

**Comment by JL2210** [comment]
Create a Git tag and a tarball of the repository. Like this:

```
git tag v2.0.0 && git push origin :refs/tags/v2.0.0
```

From there, you run this command.
A tarball of the repository will be located in your `~/Uploads` folder:

```
git checkout v2.0.0 && rm -rf .git && mkdir ~/Uploads && make clean && tar cpf ~/Uploads/svgalib-1-2.0.0.tar . && xz -z9e ~/Uploads/svgalib-1-2.0.0.tar
```

From there, go to `https://github.com/ryanmcgrath/svgalib-1/tags`, select the three dots with the light background on the `v2.0.0` box and select `Create release`. You then change the uppermost text box below `Existing tag` to say `Version 2.0.0`, and in the large text box, you write your release notes. You then go into your file manager of choice, navigate to `Uploads`, and drop `svgalib-1-2.0.0.tar.xz` on the box in your web browser that has the large down arrow in it. You click `Create release`, and you're done!

**Comment by ryanmcgrath** [comment]
OH! This is all you needed? I'm an idiot, my bad - I thought there was more needed specific to the project, and lack of context from years of not touching it was leaving me confused.

Gimme a few and you'll have what you need~

**Comment by ryanmcgrath** [comment]
Alright, should be up: https://github.com/ryanmcgrath/svgalib-1/releases/tag/2.0.0

Let me know if that's good enough for you. Thanks for the back and forth~

**Comment by JL2210** [comment]
Thank you. That looks good.
