### ISSUE TITLE
Consider posting from where you took the patches?

### ISSUE THREAD

**Issue by F3llFr0mTh3Sky** [ryanmcgrath/svgalib-1#3]
> That said, this is a 'fork' of the most recent (haha) version found on the internets, with a ton of patches from various people around the internet cobbled together.

Hello,
In case you had bookmarked or you still remember from where you took the patches, could you please post a list of them? I guess some of their authors even commented them, for e.g. they might have made them for specific reasons you might have omitted.

**Comment by ryanmcgrath** [comment]
This is like… a decade old, so no, I unfortunately have no clue lol. It’s like three laptops ago which is effectively three lifetimes ago.

**Comment by F3llFr0mTh3Sky** [comment]
Ok too bad. Anyway, thx for answering.
I'll see if I can searches for the patches sources, otherwise I'll give up.
